### ISSUE TITLE
Casting part doesn't work

### ISSUE THREAD

**Issue by scarletspider** [nlcamarillo/castDeck#9]
I'm having an issue setting up castdeck, I have the pages setup but I can't get the cast part to work.  Do you have any documentation on setting this up?

**Comment by scarletspider** [comment]
Nevermind.  Consider this resolved.

**Comment by slb** [comment]
> Nevermind. Consider this resolved.

Is Castdeck still working ? Tried to set it up 6 month ago to no avail. I assumed some change in Chromecast code broke it.
